#!/bin/sh
set -eu

#######################################################################
#
# pgAdmin III - PostgreSQL Tools
# Copyright (C) 2002 - 2016, The pgAdmin Development Team
# This software is released under the PostgreSQL Licence
#
# bootstrap - bootstrap the build system
#
#######################################################################

run_autoreconf=true
while [ $# -gt 0 ];
do
	if [ "$1" = "--skip-autoreconf" ];
	then
		run_autoreconf=false
		shift 1
	elif [ "$1" = "--" ];
	then
		shift 1
		break  # Options for autoreconf
	else
		echo "usage: ./bootstrap [--skip-autoreconf] [-- [autoreconf-param...]] " >&2
		echo >&2
		exit 1
	fi
done

# Insert the version number wherever it's needed
echo "Stamping the version number…" >&2
LONG_VER=`grep '#define VERSION_PACKAGE' pgadmin/include/version.h | awk '{print $3}'`
SHORT_VER=`echo $LONG_VER | cut -d . -f1,2`

sed -e "s/PGADMIN_LONG_VERSION/$LONG_VER/" -e "s/PGADMIN_SHORT_VERSION/$SHORT_VER/" configure.ac.in > configure.ac
sed -e "s/PGADMIN_LONG_VERSION/$LONG_VER/" -e "s/PGADMIN_SHORT_VERSION/$SHORT_VER/" pkg/mac/pgadmin.Info.plist.in > pkg/mac/pgadmin.Info.plist
sed -e "s/PGADMIN_LONG_VERSION/$LONG_VER/" -e "s/PGADMIN_SHORT_VERSION/$SHORT_VER/" pkg/mac/debug.pgadmin.Info.plist.in > pkg/mac/debug.pgadmin.Info.plist
sed -e "s/PGADMIN_LONG_VERSION/$LONG_VER/" -e "s/PGADMIN_SHORT_VERSION/$SHORT_VER/" pkg/src/build-tarball.in > pkg/src/build-tarball

sed -e "s/PGADMIN_LONG_VERSION/$LONG_VER/" -e "s/PGADMIN_SHORT_VERSION/$SHORT_VER/" docs/en_US/conf.py.in > docs/en_US/conf.py

# Add extra automake configuration file
mkdir -p config
cp -f config.rpath.in config/config.rpath

if ${run_autoreconf};
then
	echo "Configuring the build system…" >&2
	autoreconf -i "$@"
fi
