.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2025 Erin of Yukis <erin-dev@ninetailed.ninja>,
.\" (C) Copyright 2004 Raphael Enrici <blacknoz@club-internet.fr>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PGADMIN3 1 "August 28, 2025"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pgadmin3 \- Graphical administration tool for PostgreSQL
.SH SYNOPSIS
.B pgadmin3
.RI
.br

.SH DESCRIPTION
.LP
\fBpgadmin3\fP is a database design and management application for use with PostgreSQL.
.br
.LP
It includes a graphical administration interface, an SQL query tool, a
procedural code editor and much more.
.br
pgAdmin3 LTS is designed to answer the needs of most users, from writing simple
SQL queries to developing complex databases.
.br
\fBNOTE:\fP You may find useful informations in the help menu of pgAdmin3.
.br
While support for the project has been discontinued by its developers in favour
of pgAdmin 4, this codebase is still minimally maintained by users prefering a
native user interface over pgAdmin 4’s web based approach.

This manual page was written for the Debian distribution because the original
program does not have a manual page.


.SH OPTIONS
This program is a graphical application. Simply type \fBpgadmin3\fR on a
command line to launch the GUI. There are no options at all for it.

.SH SEE ALSO
.BR psql (1)

.SH AUTHOR
This manual page was originally written by Raphael Enrici <blacknoz@club-internet.fr>
for the Debian project (but may be used by others).
