name: Ubuntu build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_conf: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Update package lists
      run: sudo apt-get update

    - name: Install libraries
      run: sudo apt-get install autotools-dev libpq-dev libwxgtk3.2-dev libxslt1-dev libssh2-1-dev libxml2-dev python3-sphinx python3-sphinxcontrib.htmlhelp

    - name: Workaround Debian bug \#1112319
      run: sudo patch -u /usr/lib/python3/dist-packages/sphinx/application.py .github/workflows-helpers/01-ubuntu-sphinx-packaging.patch

    - name: Run bootstrap
      run: ./bootstrap

    - name: Run configure
      env:
        ENABLE_DEBUG: "${{ matrix.build_conf == 'Debug' && 'yes' || 'no' }}"
      run: ./configure --with-wx-version=3.2 --enable-databasedesigner --enable-debug=${{ env.ENABLE_DEBUG }}

    - name: Run make
      run: |
        make -j4 all
        sudo make install
